-- =====================================================================
-- Ecommerce Order System - Seed Data
--
-- Login credentials seeded below:
--   admin    / password   (role=1, admin)
--   testuser / password   (role=0, regular user)
--
-- Both hashes were generated by the application's BCryptPasswordEncoder
-- (strength=10) for the literal string "password".
--
-- Run after schema.sql on an empty database. Safe to re-run only after
-- truncating tables (uses fixed IDs so re-runs will conflict).
-- =====================================================================

USE ecommerce_db;

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
INSERT INTO users (id, username, password, email, phone, real_name, gender, status, role) VALUES
    (1, 'admin',    '$2a$10$rCx7Ve89lmbxrFadsappSOtBET0NeqGHW4afKr3sjSAaS2CApapsu', 'admin@example.com',    '13800000000', 'Administrator', 1, 1, 1),
    (2, 'testuser', '$2a$10$rCx7Ve89lmbxrFadsappSOtBET0NeqGHW4afKr3sjSAaS2CApapsu', 'testuser@example.com', '13800000001', 'Test User',     1, 1, 0);

-- ---------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------
INSERT INTO categories (id, name, description, status) VALUES
    (1, 'Electronics',  'Phones, laptops, accessories', 1),
    (2, 'Clothing',     'Apparel for men and women',    1),
    (3, 'Home',         'Home and kitchen goods',       1),
    (4, 'Books',        'Books and magazines',          1),
    (5, 'Sports',       'Sports and outdoor equipment', 1);

-- ---------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------
INSERT INTO products (id, name, description, price, stock, sold_count, category_id, status) VALUES
    (1, 'Wireless Headphones',     'Noise-cancelling over-ear headphones',     799.00,  49, 1, 1, 1),
    (2, 'Smartphone X',            '6.5-inch OLED, 128GB storage',            2999.00,  30, 0, 1, 1),
    (3, 'Laptop Pro 14',           '14-inch, 16GB RAM, 512GB SSD',            8999.00,  20, 0, 1, 1),
    (4, 'Cotton T-Shirt',          'Unisex 100% cotton crew-neck tee',          89.00, 200, 0, 2, 1),
    (5, 'Running Sneakers',        'Lightweight breathable running shoes',     459.00, 120, 0, 2, 1),
    (6, 'Ceramic Mug Set',         'Set of 4 ceramic mugs, 350ml each',        129.00, 100, 0, 3, 1),
    (7, 'Stainless Steel Kettle',  '1.7L electric kettle, fast boil',          199.00,  60, 0, 3, 1),
    (8, 'Spring Framework Guide',  'Comprehensive Spring Boot 3 reference',     99.00,  80, 0, 4, 1),
    (9, 'Yoga Mat',                '6mm non-slip yoga mat with carry strap',    149.00, 150, 0, 5, 1),
    (10,'Adjustable Dumbbells',    'Pair of 2.5-25kg adjustable dumbbells',   1299.00,  25, 0, 5, 1);

-- ---------------------------------------------------------------------
-- addresses (one default address for testuser)
-- ---------------------------------------------------------------------
INSERT INTO addresses (id, user_id, name, phone, province, city, district, address, is_default) VALUES
    (1, 2, 'Test User', '13800000001', 'Beijing', 'Beijing', 'Chaoyang', 'Sample Street No. 1, Building A, Apt 101', 1);

-- ---------------------------------------------------------------------
-- pending demo order for the confirmation workflow
-- ---------------------------------------------------------------------
INSERT INTO orders (
    id, order_no, user_id, total_amount, discount_amount, final_amount,
    shipping_address, shipping_phone, shipping_name,
    status, payment_status, payment_method, remark
) VALUES (
    1, 'DEMO-ORDER-001', 2, 799.00, 0.00, 799.00,
    'Beijing Beijing Chaoyang Sample Street No. 1',
    '13800000001', 'Test User',
    0, 0, 'DEMO', 'Seed order for Agent confirmation demo'
);

INSERT INTO order_items (
    id, order_id, product_id, quantity, unit_price, total_price
) VALUES (
    1, 1, 1, 1, 799.00, 799.00
);
